### ISSUE TITLE
TimeoutException in _GetElementByXPath while running the search Command

### ISSUE THREAD

**Issue by alphomeg** [joshiayush/inb#50]
`Traceback (most recent call last):
  File "c:\inb\inb2\inb\linkedin\connect\linkedinsearchconnect.py", line 482, in _GetElementByXPath
    EC.presence_of_element_located((by.By.XPATH, xpath)))
  File "C:\Users\Work\anaconda3\envs\inb\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:`

**Comment by joshiayush** [comment]
Try to use `--debug` flag with the command to get a full traceback of the exception. `TimeoutException` can be a cause of slow internet.

**Comment by alphomeg** [comment]
Hi, Thank you for responding. i've used `--debug` this is the whole traceback I got. i tracked it down to `_GetLiElementsFromPage()`. Also tried to increase the wait to 180 but same issue. `send` command is working fine

**Comment by alphomeg** [comment]
`[5976:9284:0131/101423.073:ERROR:chrome_browser_main_extra_parts_metrics.cc(227)] START: ReportBluetoothAvailability(). If you don't see the END: mess
age, this is crbug.com/1216328.
[5976:9284:0131/101423.100:ERROR:chrome_browser_main_extra_parts_metrics.cc(230)] END: ReportBluetoothAvailability()
[5976:2580:0131/101423.173:ERROR:device_event_log_impl.cc(214)] [10:14:23.173] USB: usb_device_handle_win.cc:1050 Failed to read descriptor from node
connection: A device attached to the system is not functioning. (0x1F)
[5976:9284:0131/101423.183:ERROR:chrome_browser_main_extra_parts_metrics.cc(235)] START: GetDefaultBrowser(). If you don't see the END: message, this
is crbug.com/1216328.
[5976:9284:0131/101423.240:ERROR:chrome_browser_main_extra_parts_metrics.cc(239)] END: GetDefaultBrowser()
2022-01-31 10:14:27,380:linkedin.connect.linkedinsearchconnect:ERROR:_GetElementByXPath
Traceback (most recent call last):
  File "c:\inb\inb\linkedin\connect\linkedinsearchconnect.py", line 428, in _GetElementByXPath
    EC.visibility_of_all_elements_located((by.By.XPATH, xpath)))
  File "C:\Users\Work\anaconda3\envs\inb\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:`

**Comment by joshiayush** [comment]
> `send` command is working fine.

In case you are trying to use `search` command with `--headless` flag then don't do it because it's broken at the moment. You probably want to use `search` command without `--headless` flag. The reason of `TimeoutException` is because some elements are not in the view in `--headless` mode so you want to use it in non-headless mode. I'm not going to fix this in `--headless` mode because I'm planning to make this application a web application that will run on a _ubuntu_ server so please don't except to use `search` command in conjunction with `--headless` mode.

**Comment by joshiayush** [comment]
Author is not responsive.
