### ISSUE TITLE
LinkedInChallengeException

### ISSUE THREAD

**Issue by isonupandit11** [joshiayush/inb#67]
Hi, i am getting LinkedInChallengeException at run time below is the output any fixes for this? 

`PS D:\PRJ\inb> docker run -it inb search --email mymail@gmail.com>--keyword 'Software developer' --refresh-cookies --nofollow
Password:
Repeat for confirmation:
Traceback (most recent call last):
  File "inb.py", line 190, in <module>
    Inb()
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "inb.py", line 143, in search
    linkedin = linkedin_api.LinkedIn(email,
  File "/app/api/linkedin_api.py", line 123, in __init__
    self.client.authenticate(username=username, password=password)
  File "/app/api/client.py", line 174, in authenticate
    self._fallback_authentication(username, password)
  File "/app/api/client.py", line 142, in _fallback_authentication
    raise linkedin_api_exceptions.LinkedInChallengeException(
api.exceptions.LinkedInChallengeException: CHALLENGE`

**Comment by joshiayush** [comment]
`LinkedInChallengeException` is basically made for the situations when the login does not PASS! So, please cross-check if the problem is in login...

Pass any problem occurred in the docker environment to @ologbonowiwi .

Thanks for using inb

**Comment by BaptisteGarcin** [comment]
same here

**Comment by wesleymatosdev** [comment]
@BaptisteGarcin @isonupandit11, are you having this issue only on docker, or by executing it locally, it also occurs?

**Comment by AnshulRaghav** [comment]
@ologbonowiwi  it is happening on docker

**Comment by jets-creator** [comment]
same

**Comment by wesleymatosdev** [comment]
yo guys 👋🏽 quick update on this, I created the Dockerfile to this a long time ago, I have not been using this tool probably for years now, and I don't have the bandwidth to keep on supporting and debugging this

since that's open source, we appreciate it if anyone can try to take on this and give a shot at fixing it.

if there's anything you did not fully get or need clarification on, or if you need further implementation or something else that I can assist with, I'll be happy to help.

thanks for using the project!
